services:
  web:
    build: .
    tty: true
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "9091:8080"
